version: "3.9"
services:
  nemo_contailar:
    container_name: asj-exp
    image: nemo19_nemo_contailar
    build:
      shm_size: "8gb"
    shm_size: "8gb"
    environment:
      - PYTHONPATH=/opt/ml
    ports:
      - 10028:10028
    volumes:
      - /mnt/disks/disk-3/mikawa/asj:/mnt/disks/disk-3/mikawa/asj
    working_dir: //mnt/disks/disk-3/mikawa/asj
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: [ '0', '1' ]
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
